import type { ApiEndpointDefinition, ApiRequest, ApiContext } from "@starkeep/shared-space-api";
import type { StarkeepId } from "@starkeep/core";
import { sha256Hex } from "../helpers/sha256";
import { createImageRecord } from "../../data/image-record";
import { PROVENANCE_GENERATOR_ID } from "../../metadata/provenance-generator";
import { USER_AUTHORED_GENERATOR_ID } from "../../metadata/user-authored-generator";
import { IMAGE_RECORD_TYPE } from "../../manifest";

interface UploadBody {
  fileBase64: string;
  mimeType: string;
  provenance: {
    originalFilename: string;
    googlePhotosId?: string | null;
    sourceImageId?: string | null;
    cropX?: number | null;
    cropY?: number | null;
    cropWidth?: number | null;
    cropHeight?: number | null;
  };
  userAuthored: {
    title: string;
    caption: string;
  };
}

/**
 * Stores raw image bytes, creates a DataRecord, and writes syncable metadata
 * (provenance, user-authored). Non-syncable metadata (dimensions, EXIF,
 * thumbnail) is generated by the calling SDK layer via sdk.metadata.generateAll()
 * after this handler returns.
 *
 * Returns { imageId } so the caller can run generators and fetch the full AppImage.
 */
export const uploadImageHandler: ApiEndpointDefinition = {
  namespace: "photos",
  version: "v1",
  path: "photos/upload",
  method: "POST",
  handler: async (request: ApiRequest, context: ApiContext) => {
    const body = request.body as Partial<UploadBody> | undefined;
    if (!body?.fileBase64) return { status: 400, body: { error: "fileBase64 is required" } };
    if (!body.mimeType) return { status: 400, body: { error: "mimeType is required" } };
    if (!body.provenance?.originalFilename) {
      return { status: 400, body: { error: "provenance.originalFilename is required" } };
    }

    const fileBytes = base64ToBytes(body.fileBase64);
    const contentHash = await sha256Hex(fileBytes);
    const objectStorageKey = `images/${contentHash.slice(0, 2)}/${contentHash}`;

    await context.objectStorageAdapter.put(objectStorageKey, fileBytes, {
      contentType: body.mimeType,
    });

    const record = createImageRecord({
      mimeType: body.mimeType,
      objectStorageKey,
      contentHash,
      sizeBytes: fileBytes.length,
      clock: context.clock,
      ownerId: context.ownerId,
    });

    await context.databaseAdapter.put(record);

    const now = context.clock.now();

    await context.databaseAdapter.upsertSyncableMetadata({
      targetId: record.id,
      targetType: IMAGE_RECORD_TYPE,
      generatorId: PROVENANCE_GENERATOR_ID,
      generatorVersion: 1,
      updatedAt: now,
      inputHash: "",
      value: {
        originalFilename: body.provenance.originalFilename,
        googlePhotosId: body.provenance.googlePhotosId ?? null,
        sourceImageId: body.provenance.sourceImageId ?? null,
        cropX: body.provenance.cropX ?? null,
        cropY: body.provenance.cropY ?? null,
        cropWidth: body.provenance.cropWidth ?? null,
        cropHeight: body.provenance.cropHeight ?? null,
      },
    });

    const defaultTitle = body.provenance.originalFilename.replace(/\.[^.]+$/, "");

    await context.databaseAdapter.upsertSyncableMetadata({
      targetId: record.id,
      targetType: IMAGE_RECORD_TYPE,
      generatorId: USER_AUTHORED_GENERATOR_ID,
      generatorVersion: 1,
      updatedAt: now,
      inputHash: "",
      value: {
        caption: body.userAuthored?.caption ?? "",
        title: body.userAuthored?.title || defaultTitle,
        dateTakenOverride: null,
      },
    });

    return { status: 201, body: { imageId: record.id as string } };
  },
};

function base64ToBytes(base64: string): Uint8Array {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}
